name: 功能建議
description: 提出新功能或改善建議
title: "[Feature] "
labels: ["enhancement"]
body:
  - type: textarea
    id: need
    attributes:
      label: 使用情境
      description: 想解決什麼問題？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 建議方案
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: 考慮過的替代方案
